"""create sign_detection

Revision ID: 30c13cb53dea
Revises: 
Create Date: 2026-03-03 13:34:50.030687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30c13cb53dea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign_detection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('detected_sign', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sign_detection_detected_sign'), 'sign_detection', ['detected_sign'], unique=False)
    op.create_index(op.f('ix_sign_detection_is_deleted'), 'sign_detection', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sign_detection_session_id'), 'sign_detection', ['session_id'], unique=False)
    op.create_index(op.f('ix_sign_detection_user_id'), 'sign_detection', ['user_id'], unique=False)
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.create_unique_constraint(None, 'post', ['id'])
    op.create_unique_constraint(None, 'rate_limit', ['id'])
    op.create_unique_constraint(None, 'tier', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'tier', type_='unique')
    op.drop_constraint(None, 'rate_limit', type_='unique')
    op.drop_constraint(None, 'post', type_='unique')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.drop_index(op.f('ix_sign_detection_user_id'), table_name='sign_detection')
    op.drop_index(op.f('ix_sign_detection_session_id'), table_name='sign_detection')
    op.drop_index(op.f('ix_sign_detection_is_deleted'), table_name='sign_detection')
    op.drop_index(op.f('ix_sign_detection_detected_sign'), table_name='sign_detection')
    op.drop_table('sign_detection')
    # ### end Alembic commands ###
