"""Add version support.

Revision ID: 42076eab43ab
Revises: 7d5bfd91c20b
Create Date: 2026-03-08 09:37:19.649626
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "42076eab43ab"
down_revision: str | None = "7d5bfd91c20b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_blacklist_token"), table_name="token_blacklist")
    op.drop_table("token_blacklist")
    op.create_unique_constraint(None, "post", ["id"])
    op.create_unique_constraint(None, "rate_limit", ["id"])
    op.create_unique_constraint(None, "sign_detection", ["id"])
    op.add_column("signs", sa.Column("cloudinary_public_id", sa.String(length=500), nullable=True))
    op.add_column("signs", sa.Column("file_size", sa.Integer(), nullable=True))
    op.add_column("signs", sa.Column("width", sa.Integer(), nullable=True))
    op.add_column("signs", sa.Column("height", sa.Integer(), nullable=True))
    op.add_column("signs", sa.Column("mime_type", sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, "signs", ["id"])
    op.create_unique_constraint(None, "tier", ["id"])
    op.create_unique_constraint(None, "user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "tier", type_="unique")
    op.drop_constraint(None, "signs", type_="unique")
    op.drop_column("signs", "mime_type")
    op.drop_column("signs", "height")
    op.drop_column("signs", "width")
    op.drop_column("signs", "file_size")
    op.drop_column("signs", "cloudinary_public_id")
    op.drop_constraint(None, "sign_detection", type_="unique")
    op.drop_constraint(None, "rate_limit", type_="unique")
    op.drop_constraint(None, "post", type_="unique")
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("token_blacklist_pkey")),
    )
    op.create_index(op.f("ix_token_blacklist_token"), "token_blacklist", ["token"], unique=True)
    # ### end Alembic commands ###
